# Generated by Django 4.0.4 on 2022-05-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_publisheddate', models.DateField(auto_now=True)),
                ('bookname', models.CharField(max_length=150)),
                ('book_filename', models.CharField(max_length=150)),
            ],
        ),
    ]
